### ISSUE TITLE
Tie this repo to npm 

### ISSUE THREAD

**Issue by travis5491811** [Adam-Jimenez/vue2-jsoneditor#2]
Tie this repo to npm

https://www.npmjs.com/package/vue2-jsoneditor

**Comment by Adam-Jimenez** [comment]
done

**Comment by travis5491811** [comment]
@Adam-Jimenez maybe takes a min to update? Still not showing this repo as connected to that project.

![github_not_connected](https://user-images.githubusercontent.com/41482601/55990121-e3d72400-5c74-11e9-80df-361795d4cf4c.png)

**Comment by travis5491811** [comment]
npm missing this. 
![github_missing_this](https://user-images.githubusercontent.com/41482601/55990208-1d0f9400-5c75-11e9-977c-c7634c115fe3.png)

**Comment by Adam-Jimenez** [comment]
check version 1.0.6 for update
